batch_4_sections = {
    # PART XVII
    "National professional regulation": "(1) The Council shall be the sole national authority responsible for setting the standards of professional competence and registering built environment practitioners.\n(2) No county government shall enact legislation attempting to establish parallel professional registration boards or overlapping competency standards for built environment professionals.",
    "County development control": "(1) County governments retain the exclusive constitutional mandate for local physical planning, zoning, and the issuance of development permissions (building approvals) within their respective jurisdictions.\n(2) Nothing in this Act shall be construed as prejudicing the exclusive mandate of County Governments over county planning and development control as provided under Part 2 of the Fourth Schedule to the Constitution.",
    "Information sharing": "(1) The Council and the county governments shall establish a seamless, digitized mechanism for the real-time sharing of information.\n(2) The Council must provide counties with live access to the National Register to verify the status of professionals submitting development applications.",
    "Professional verification for approvals": "(1) A county government shall not approve any architectural, engineering, or physical planning drawings unless the drawings bear the cryptographically secure digital signature of a registered professional in good standing.\n(2) Any county official who approves drawings submitted by an unregistered person or a quack commits an offence and is liable to prosecution under this Act.",
    "Coordination mechanisms": "To ensure harmonious implementation of the built environment framework, the Council shall establish an Inter-Governmental Built Environment Coordination Forum, comprising representatives from the Council, the Council of Governors, and relevant national ministries.",
    "Avoidance of duplication": "The Council and county governments must align their inspection schedules and digital submission portals to prevent the duplication of regulatory burdens on developers and professionals, striving for a unified 'single-window' approval system.",
    "Intergovernmental cooperation": "In the event of a severe structural failure or environmental disaster, the Council's Inspectorate and the respective county government's disaster management unit shall establish a joint task force to investigate the cause and assign professional culpability.",

    # PART XVIII
    "Funds": "(1) The funds of the Council shall consist of—\n(a) monies appropriated by Parliament for the purposes of the Council;\n(b) registration fees, practising certificate fees, and firm registration fees;\n(c) fines levied by the Disciplinary Committee;\n(d) grants, gifts, or donations accepted by the Council.\n(2) All funds shall be managed strictly in accordance with the Public Finance Management Act.",
    "Built environment safety levy": "(1) The Cabinet Secretary, in consultation with the Council and the National Treasury, may by notice in the Gazette impose a Built Environment Safety Levy.\n(2) The Levy shall be calculated as a prescribed percentage not exceeding 0.1 percent of the total contract value of any high-risk built environment project.\n(3) The proceeds of the Levy shall be ring-fenced and used exclusively to fund the proactive site inspection, enforcement, and compliance activities of the Inspectorate Directorate.",
    "Fees": "(1) The Council may, by notice in the Gazette, prescribe the various fees payable for registration, examinations, certificates, and other services rendered under this Act.\n(2) The fee structure must be equitable and must not be used as an exclusionary barrier to entry into the professions.",
    "Annual estimates": "(1) At least three months before the commencement of each financial year, the Council shall cause to be prepared estimates of the revenue and expenditure of the Council for that year.\n(2) The annual estimates shall be submitted to the Cabinet Secretary for approval before the commencement of the financial year, in strict compliance with the Public Finance Management Act.",
    "Financial management": "The Council shall cause to be kept all proper books and records of accounts of the income, expenditure, assets, and liabilities of the Council.",
    "Audit": "(1) The accounts of the Council shall be audited and reported upon annually by the Auditor-General in accordance with the Public Audit Act.\n(2) The Council must submit its financial statements to the Auditor-General within three months after the end of each financial year.",
    "Annual reports": "The Council shall, within three months after the end of each financial year, prepare and submit to the Cabinet Secretary a comprehensive annual report covering its operations, disciplinary actions, and financial performance.",
    "Performance reporting": "The annual report must include measurable performance indicators, including the number of professionals registered, the number of site inspections conducted, the resolution rate of disciplinary cases, and the prevalence of quackery.",
    "Public accountability": "(1) The Council shall publish its annual report, audited financial statements, and a summary of disciplinary actions on its website for public scrutiny.\n(2) The Council must convene an Annual General Meeting open to all registered professionals to report on its stewardship.",
    "Parliamentary oversight": "The Cabinet Secretary shall lay the annual report and audited financial statements of the Council before the National Assembly within thirty days of receiving them, ensuring ultimate democratic oversight of the regulatory framework.",

    # PART XIX
    "Power to make regulations": "(1) The Cabinet Secretary may, in consultation with the Council, make regulations generally for the better carrying into effect of the provisions of this Act.\n(2) Without prejudice to the generality of subsection (1), regulations may prescribe detailed procedures for elections, disciplinary hearings, continuous professional development, and the recognition of foreign qualifications.",
    "Standards": "(1) The Council may, by notice in the Gazette, publish mandatory technical and ethical standards for the built environment professions.\n(2) These standards shall have the force of law and any breach thereof shall constitute professional misconduct.",
    "Consultation": "Before making any regulations or publishing any mandatory standards, the Cabinet Secretary and the Council must engage in extensive consultations with constituent professional regulators, industry associations, academia, and consumer protection bodies.",
    "Public participation": "All proposed regulations and standards must be subjected to rigorous public participation in strict compliance with Article 10 of the Constitution. The Council must publish draft regulations and invite written memoranda from the public.",
    "Publication": "All regulations, standards, and rules made under this Act must be published in the Kenya Gazette and made freely available on the Council's official digital platform.",
    "Review": "The Council shall review all regulations and standards at least once every five years to ensure they remain relevant to technological advancements, climate change imperatives, and shifting economic realities.",
    "Limits on delegated powers": "Any regulation or standard that attempts to levy unauthorized taxes, impose retroactive criminal penalties, or usurp the constitutional functions of county governments shall be null and void to the extent of the inconsistency.",

    # PART XX
    "Existing registrations": "Any person who, immediately before the commencement of this Act, was validly registered by the Board of Registration of Architects and Quantity Surveyors (BORAQS), the Engineers Board of Kenya (EBK), or any other recognized statutory body, shall automatically be deemed to be registered under this Act in the equivalent category.",
    "Existing practising certificates": "All practising certificates and licenses issued under repealed or amended Acts shall remain valid until their stipulated expiry date, after which they must be renewed under the provisions of this Act.",
    "Existing professionals": "Existing professionals transitioning into this new framework shall not be required to retake professional examinations, but must immediately comply with the new continuous professional development and indemnity insurance requirements.",
    "Existing technicians and technologists": "Technicians and technologists currently practicing without statutory recognition shall be granted a grace period of twenty-four months to apply for formal registration under this Act, subject to a competency assessment.",
    "Existing firms": "All built environment consulting firms currently registered under previous regimes must re-register with the Council under Part VII of this Act within twelve months of commencement.",
    "Existing examinations": "Candidates currently enrolled in professional examination processes under existing statutory boards shall be allowed to complete their examinations under the old rules, provided they do so within three years of the commencement of this Act.",
    "Existing disciplinary matters": "Any disciplinary inquiry or legal proceeding pending before an existing statutory board at the commencement of this Act shall be concluded by that board as if this Act had not been enacted, and any resulting sanctions shall be enforced by the Council.",
    "Existing regulations": "All regulations, bylaws, and standards made under any repealed Act shall remain in force, mutatis mutandis, until specifically revoked and replaced by new regulations made under this Act.",
    "Transitional licences": "The Council may issue transitional licenses to distinct groups of practitioners (such as interior designers or landscape architects) whose professions were previously unregulated, while their formal registration frameworks are being finalized.",
    "Repeal of Cap. 525": "The Architects and Quantity Surveyors Act (Cap. 525) is hereby repealed.",
    "Consequential amendments": "The Acts specified in the Seventh Schedule (including the Physical and Land Use Planning Act and the Engineers Act) are amended in the manner specified in that Schedule to align them with the overarching mandate of the Council.",
    "Savings provisions": "Nothing in the repeal or amendment of existing laws shall affect the validity of any building approval granted, or contract executed, prior to the commencement of this Act.",
    "Review of Act": "The Cabinet Secretary shall, in consultation with the Council and Parliament, conduct a comprehensive review of the implementation and effectiveness of this Act within five years of its commencement."
}
