batch_3_sections = {
    # PART XIII
    "Establishment of the Inspectorate": "(1) There is established an Inspectorate Directorate within the Council.\n(2) The Directorate's primary mandate is to monitor compliance with this Act and prevent the unlawful practice of built environment professions.",
    "Powers of entry and inspection": "(1) An authorized inspector may, at any reasonable time and without prior warrant, enter any active construction site, fabrication yard, or professional office to verify compliance with this Act.\n(2) The inspector must produce official identification and clearly state the purpose of the inspection to the site manager or owner.",
    "Production of documents": "(1) During an inspection, an authorized inspector may demand the immediate production of approved structural drawings, site meeting minutes, logbooks, and the practicing certificates of the supervising professionals.\n(2) Failure or refusal to produce these documents upon lawful demand constitutes an offence.",
    "Site stop orders": "(1) Where an inspector determines that a built environment project is being executed by unregistered persons, or poses an imminent and severe risk of structural failure or environmental disaster, the inspector may issue an immediate Site Stop Order.\n(2) A Site Stop Order compels the immediate cessation of all works until the Council verifies that the safety breaches have been rectified by registered professionals.",
    "Seizure of equipment": "In extreme cases of persistent quackery or defiance of a Site Stop Order, an inspector, accompanied by law enforcement officers, may seize construction equipment or architectural plans being used to perpetrate the offence.",
    "Enforcement notices": "For minor regulatory breaches, an inspector may issue an Enforcement Notice, granting the offender a specified period (not exceeding fourteen days) to rectify the breach before formal disciplinary or criminal proceedings are instituted.",
    "Collaboration with police and county inspectorates": "(1) The Inspectorate shall actively collaborate with the National Police Service, the Directorate of Criminal Investigations, and County Government Inspectorates to execute its mandate.\n(2) County governments are statutorily required to assist the Council's inspectors in enforcing Site Stop Orders within their jurisdictions.",

    # PART XIV
    "Unlawful practice and quackery": "(1) Any person who engages in the practice of a built environment profession, or undertakes reserved professional work without holding a valid registration and practising certificate, commits the offence of quackery.\n(2) A person convicted of quackery is liable to a fine not exceeding five million shillings, or imprisonment for a term not exceeding five years, or to both.",
    "Masquerading": "Any person who assumes or uses any title, designation, or suffix prescribed under this Act (such as 'Architect', 'Engineer', or 'Quantity Surveyor') while not being registered, with the intent to deceive the public, commits an offence and is liable to severe penalties.",
    "False representation": "A person who procures, or attempts to procure, registration under this Act by making a false representation, presenting forged academic certificates, or falsifying logbooks commits an offence and is liable to imprisonment for a term not exceeding three years.",
    "False registration documents": "Any person who forges, alters, or counterfeits a registration certificate, practising certificate, or digital verification seal issued by the Council commits a felony and is liable upon conviction to imprisonment for a term not exceeding seven years.",
    "Unauthorised use of professional titles": "(1) The specific titles associated with the built environment professions are protected by law.\n(2) Unregistered corporate entities are strictly prohibited from using protected titles (e.g., 'Engineering Solutions Ltd') in their registered company names without clearance from the Council.",
    "False certification": "A registered professional who knowingly signs, seals, or digitally certifies structural drawings, completion certificates, or environmental impact assessments that they know to be false, fundamentally flawed, or unsafe, commits an offence and is liable to imprisonment for a term not exceeding ten years.",
    "Corporate offences": "(1) Where an offence under this Act is committed by a corporate entity or registered firm, every director, principal partner, and the designated Responsible Professional shall be deemed guilty of the offence unless they can prove it was committed without their knowledge or consent.\n(2) The corporate entity itself may be fined up to ten million shillings.",
    "Obstruction of inspectors": "Any person who physically obstructs, assaults, threatens, or attempts to bribe an authorized inspector or Council official in the execution of their statutory duties commits an offence and is liable to immediate arrest.",
    "General penalties": "Any person convicted of an offence under this Act for which no specific penalty is provided shall be liable to a fine not exceeding two million shillings, or imprisonment for a term not exceeding two years, or to both.",
    "Continuing offences": "Where an offence under this Act is of a continuing nature (such as ignoring a Site Stop Order), the offender shall be liable to an additional daily fine of one hundred thousand shillings for every day the offence continues after the initial conviction.",

    # PART XV
    "Accreditation": "(1) The Council shall be the sole statutory authority responsible for the professional accreditation of built environment academic programs in Kenyan universities and tertiary institutions.\n(2) No institution shall offer a program purporting to lead to professional registration without the prior accreditation of the Council.",
    "Competency standards": "The Council, in consultation with industry stakeholders and academia, shall periodically publish and update the minimum competency standards and syllabi required for accreditation, ensuring alignment with global technological advancements.",
    "Professional education": "Accredited educational programs must integrate practical application, professional ethics, constitutional values, and environmental sustainability into their core curricula.",
    "Practical training": "(1) The Council shall prescribe the modalities for statutory pupilage and practical training for graduates.\n(2) Registered professional firms must provide structured mentorship to graduates. The Council may levy a training fee on firms that refuse to take on trainees.",
    "Professional examinations": "(1) To bridge the gap between academic theory and professional practice, the Council shall administer rigorous Professional Practice Examinations.\n(2) The examinations must test the candidate's understanding of local laws, building codes, contract administration, and project risk management.",
    "Continuing professional development": "The Council shall establish a mandatory CPD framework requiring professionals to undertake ongoing training in emerging areas such as climate-resilient design, building information modelling (BIM), and alternative dispute resolution.",
    "Research": "(1) The Council shall allocate a percentage of its annual revenue to fund research into locally appropriate building materials, affordable housing technologies, and sustainable urban planning.\n(2) The Council may partner with universities and research institutes to execute this mandate.",
    "Innovation": "The Council shall establish mechanisms to evaluate and approve novel building materials, non-standard structural designs, and innovative construction methodologies that are not yet covered by the National Building Code, provided they are demonstrated to be safe by registered specialists.",
    "Indigenous knowledge": "The Council shall formally recognize, document, and integrate proven indigenous and vernacular building knowledge into the competency frameworks, provided such techniques meet modern structural and safety criteria.",
    "Emerging technologies": "The Council shall proactively develop regulations governing the application of emerging technologies in the built environment, including artificial intelligence in design, 3D printing of structures, and drone-assisted site surveying.",

    # PART XVI
    "Public safety": "(1) The overarching priority of all built environment interventions shall be the preservation of public safety.\n(2) No professional or firm shall authorize or participate in a project that poses an unacceptable risk of structural collapse, fire outbreak, or toxic exposure.",
    "Building and life safety": "(1) The Council shall collaborate with the relevant state departments to enforce a National Building Code.\n(2) All architectural and engineering designs must incorporate comprehensive life-safety measures, including adequate fire escapes, structural redundancies, and safe material selection.",
    "Accessibility": "(1) Every public building, commercial facility, and public infrastructure project designed or constructed under this Act must strictly comply with universal design standards.\n(2) Failure to provide unhindered accessibility for persons with disabilities, the elderly, and children constitutes a breach of the professional code of conduct and violates Article 54 of the Constitution.",
    "Universal design": "Professionals must adopt a universal design approach, ensuring that environments are inherently accessible to all people regardless of their age, size, or physical ability, without the need for adaptation or specialized design.",
    "Environmental responsibility": "(1) The design and execution of built environment projects must align with the Environmental Management and Coordination Act (EMCA).\n(2) Professionals have a duty to minimize ecological disruption, protect riparian reserves, and prevent the pollution of air and water resources during construction.",
    "Climate resilience": "All major infrastructure and urban planning projects must incorporate climate resilience modelling, ensuring that designs can withstand anticipated extreme weather events, flooding, and temperature anomalies caused by climate change.",
    "Sustainable development": "Professionals must advocate for sustainable development practices, including the optimization of land use, the preservation of heritage sites, and the adoption of circular economy principles in the selection of building materials.",
    "Disaster resilience": "(1) In regions prone to natural disasters (such as seismic zones or flood plains), specialized professionals must certify that the designs incorporate specific disaster-resilience mechanisms.\n(2) The Council shall publish specific competency guidelines for disaster-resilient design.",
    "Energy and resource efficiency": "All building designs must prioritize energy efficiency, passive cooling, natural lighting, and water conservation. The Council may mandate energy-audits for high-consumption projects."
}
