batch_5_sections = {
    # PART III: REGULATED BUILT ENVIRONMENT PROFESSIONS
    "Designation of professions": "(1) For the purposes of this Act, the regulated built environment professions shall initially include Architecture, Engineering, Quantity Surveying, Physical and Land Use Planning, Landscape Architecture, Construction Management, and Interior Design.\n(2) The Cabinet Secretary may, upon the recommendation of the Council, by notice in the Gazette, designate any other discipline as a regulated built environment profession.",
    "Recognition of existing statutory professional regulators": "(1) Any statutory board established under any written law to regulate a specific built environment profession prior to the commencement of this Act shall be recognized as a Profession-Specific Board under the Council.\n(2) Such boards shall continue to exercise technical oversight over their respective disciplines, subject to the overarching policy and regulatory framework established by the Council.",
    "Profession-specific regulatory autonomy": "Despite the establishment of the umbrella Council, Profession-Specific Boards shall retain autonomy in setting discipline-specific academic curricula, conducting discipline-specific professional examinations, and managing peer-review mechanisms within their specialized scope of practice.",
    "Recognition of new professions": "(1) A group representing an unregulated built environment discipline may apply to the Council for formal designation as a recognized profession.\n(2) The Council shall evaluate the application based on the discipline's impact on public safety, the maturity of its academic foundation, and the necessity of statutory regulation to protect the public interest.",
    "Relationship between umbrella Council and profession regulators": "(1) The Council shall serve as the apex regulatory authority, providing a unified code of conduct, a centralized registration portal, and a single appellate mechanism (the Tribunal).\n(2) In the event of a conflict between a directive of the Council and a directive of a Profession-Specific Board on matters of public safety or cross-disciplinary coordination, the directive of the Council shall prevail.",

    # PART XIV: OFFENCES AND PENALTIES
    "Unlawful practice and quackery": "(1) A person who engages in the practice of a built environment profession, or undertakes reserved professional work, without holding a valid registration and practising certificate commits an offence.\n(2) A person convicted of an offence under this section is liable to a fine not exceeding five million shillings, or to imprisonment for a term not exceeding five years, or to both.",
    "Masquerading": "(1) A person who is not registered under this Act, but who uses any name, title, addition, or description implying that they are so registered, commits an offence.\n(2) A person convicted under this section is liable to a fine not exceeding three million shillings or to imprisonment for a term not exceeding three years.",
    "False representation": "Any person who procures or attempts to procure registration under this Act by making a false or fraudulent representation, whether verbally or in writing, commits an offence and is liable to imprisonment for a term not exceeding three years.",
    "False registration documents": "(1) Any person who forges, alters, or counterfeits any registration certificate, practising certificate, or digital seal issued under this Act commits an offence.\n(2) A person convicted of forgery under this section is liable to a fine not exceeding five million shillings or to imprisonment for a term not exceeding seven years, or to both.",
    "Unauthorised use of professional titles": "A person shall not use the titles 'Architect', 'Engineer', 'Quantity Surveyor', 'Physical Planner', or any other legally protected title prescribed by the Council unless they are formally registered in the respective professional category. Contravention of this section constitutes an offence.",
    "False certification": "(1) A registered professional who issues a statutory compliance declaration, a certificate of practical completion, or a structural safety certificate knowing it to be false or recklessly without verifying its accuracy, commits an offence.\n(2) A professional convicted under this section shall, in addition to a fine not exceeding ten million shillings, have their registration permanently revoked.",
    "Corporate offences": "(1) Where an offence under this Act is committed by a body corporate or a firm, every director, partner, or principal officer of the firm at the time the offence was committed shall be deemed to have committed the offence.\n(2) It shall be a defense if the director proves that the offence was committed without their knowledge and that they exercised all due diligence to prevent the commission of the offence.",
    "Obstruction of inspectors": "Any person who willfully obstructs, hinders, or assaults an authorized inspector in the execution of their duties, or who fails to comply with a lawful Site Stop Order, commits an offence and is liable to a fine not exceeding two million shillings or imprisonment for two years.",
    "General penalties": "Any person who contravenes any provision of this Act for which no specific penalty is provided commits an offence and is liable on conviction to a fine not exceeding one million shillings or to imprisonment for a term not exceeding one year.",
    "Continuing offences": "Where an offence under this Act is of a continuing nature, the convicted person shall be liable to an additional fine not exceeding one hundred thousand shillings for each day during which the offence continues after the initial conviction.",

    # PART XVI: BUILT ENVIRONMENT, SAFETY, ACCESSIBILITY AND SUSTAINABILITY
    "Public safety": "(1) The paramount consideration in the planning, design, and execution of any built environment project shall be the protection of public safety, health, and welfare.\n(2) Economic considerations or client directives shall not override a professional's statutory duty to ensure public safety.",
    "Building and life safety": "All structural and architectural designs for high-risk buildings must strictly incorporate fail-safe mechanisms for structural integrity, fire compartmentation, and emergency egress, in strict accordance with the National Building Code.",
    "Accessibility": "(1) A registered professional shall not design, approve, or supervise the construction of any public building or infrastructure that does not provide unhindered access for persons with disabilities.\n(2) Non-compliance with statutory accessibility standards constitutes gross professional misconduct.",
    "Universal design": "The Council shall promote the adoption of universal design principles, ensuring that the built environment is usable by all people, to the greatest extent possible, without the need for adaptation or specialized design.",
    "Environmental responsibility": "(1) Professionals must evaluate and mitigate the environmental impact of their projects, ensuring compliance with the Environmental Management and Coordination Act.\n(2) The Council may discipline a professional who recklessly designs or executes a project resulting in severe ecological degradation.",
    "Climate resilience": "The Council shall mandate the integration of climate resilience parameters—such as extreme weather loading, flood mitigation, and heat stress adaptation—into the standard design codes for all critical infrastructure.",
    "Sustainable development": "Built environment professionals have a statutory duty to promote sustainable development by prioritizing resource-efficient designs, minimizing construction waste, and advocating for the use of low-carbon materials.",
    "Disaster resilience": "(1) Infrastructure located in seismically active zones or flood plains must be designed by registered specialists to withstand anticipated disaster scenarios.\n(2) The Council shall maintain a register of structural specialists certified for disaster-resilient design.",
    "Energy and resource efficiency": "The design of commercial and public buildings must incorporate passive design strategies, energy-efficient systems, and water conservation technologies to minimize the lifecycle carbon footprint of the built environment."
}
